version: "3.8"

services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - frontend  # Optional depending on the order you want to build the services

networks:
  app-network:
    driver: bridge
