# Fly.io application configuration

app = "product-comparison"  # Change this to the name of your app on Fly.io


# Docker build configuration
[build]
  dockerfile = "Dockerfile"  # Ensure this is the correct relative path to your Dockerfile

[env]
  BACKEND_URL = "http://localhost:3003"  # Backend URL for frontend use

[experimental]
  auto_restart = true

# Services for frontend and backend
[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[services]]
  internal_port = 3003
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 3003